# Generated by Django 5.0.6 on 2024-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HMS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentuser",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
