# Generated by Django 5.0.6 on 2024-07-21 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HMS", "0002_alter_studentuser_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15, null=True)),
                ("image", models.FileField(null=True, upload_to="")),
                ("gender", models.CharField(max_length=15, null=True)),
                ("company", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=15, null=True)),
                ("status", models.CharField(max_length=15, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
